import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Intercambio Cortesiano",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_navidad.png",  // Ruta correcta a la imagen
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
